export enum Role {
  FIELD_ENGINEER = 'Field Engineer',
  DATA_SCIENTIST = 'Data Scientist',
}

export interface AnalysisResult {
  defectType: string;
  severity: 'Low' | 'Medium' | 'High' | 'Critical';
  confidence: number;
  instructions: string;
  isQualitySufficient: boolean;
  missingAngles?: string[];
}

export interface CapturedItem {
  id: string;
  timestamp: number;
  imageUrl: string; // The original captured image
  annotatedImageUrl?: string; // The image generated by Nano Banana Pro
  analysis: AnalysisResult | null;
  status: 'pending' | 'approved' | 'rejected';
  metadata: {
    machineId: string;
    component: string;
    location: string;
  };
}

export interface DatasetStats {
  totalSamples: number;
  classDistribution: { name: string; value: number }[];
  qualityScore: number;
  pendingReview: number;
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'ai' | 'system';
  role: Role | 'System';
  text: string;
  timestamp: number;
}

export interface ProjectGoal {
  id: string;
  title: string;
  targetCount: number;
  currentCount: number;
  deadline: string;
  status: 'active' | 'completed' | 'at-risk';
  description: string;
}
